# Generated by Django 3.2.6 on 2024-10-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuento', '0002_auto_20241018_0406'),
        ('usuarioPadreFamilia', '0002_rename_user_name_usuariopadrefamilia_username_and_more'),
        ('recibo', '0003_auto_20241018_0406'),
        ('cronograma', '0002_cronograma_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='estado_pago',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='usuario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioPadreFamilia.usuariopadrefamilia'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='mes',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('tipo_pago', models.CharField(default='', max_length=100)),
                ('nombre_pago', models.CharField(default='Pago genérico', max_length=100)),
                ('cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados', to='cronograma.cronograma')),
                ('descuentos', models.ManyToManyField(related_name='pagos_cronograma_app', to='descuento.Descuento')),
                ('recibo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_cronograma_app', to='recibo.recibo')),
                ('usuario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados', to='usuarioPadreFamilia.usuariopadrefamilia')),
            ],
        ),
    ]
