# Generated by Django 4.2.16 on 2024-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recibo', models.IntegerField(default=0)),
                ('fecha_emision', models.DateField()),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('VENCIDO', 'Vencido'), ('POR PAGAR', 'Por pagar'), ('PAGADO', 'Pagado')], default='POR PAGAR', max_length=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
