# Generated by Django 5.1.1 on 2024-10-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='saldo',
            new_name='saldo_pendiente',
        ),
    ]
