# Generated by Django 3.2.6 on 2024-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0002_rename_saldo_recibo_saldo_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='id_recibo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='codigo_barras',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.CharField(choices=[('VENCIDO', 'Vencido'), ('POR PAGAR', 'Por pagar'), ('PAGADO', 'Pagado')], default='POR PAGAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
