# Generated by Django 5.1.1 on 2024-10-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPadreFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estudiante_relacionado', models.CharField(max_length=100)),
            ],
        ),
    ]
