# Generated by Django 3.2.6 on 2024-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarioPadreFamilia', '0002_rename_user_name_usuariopadrefamilia_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopadrefamilia',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='usuariopadrefamilia',
            name='cronogramas',
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='estudiante_relacionado',
            field=models.CharField(default='No reconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_padrefamilia_set', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='usuariopadrefamilia',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_padrefamilia_permissions_set', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usuariopadrefamilia',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
