# Generated by Django 4.2.16 on 2024-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_descuento', models.IntegerField(default=0)),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
