# Generated by Django 3.2.6 on 2024-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='id_descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fecha_aplicacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
