# Generated by Django 4.2.16 on 2024-10-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronograma', '0001_initial'),
        ('recibo', '0001_initial'),
        ('descuento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_pago', models.CharField(default='PENDIENTE', max_length=20)),
                ('tipo_pago', models.CharField(default='Pendiente', max_length=100)),
                ('nombre_pago', models.CharField(default='Pago genérico', max_length=100)),
                ('cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados_pago', to='cronograma.cronograma')),
                ('descuentos', models.ManyToManyField(related_name='pagos_cronograma', to='descuento.descuento')),
                ('recibo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_pago', to='recibo.recibo')),
            ],
        ),
    ]
