# Generated by Django 5.1.1 on 2024-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuento', '0001_initial'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='descuentos',
            field=models.ManyToManyField(to='descuento.descuento'),
        ),
    ]
