# Generated by Django 5.1.1 on 2024-10-03 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_pago_descuentos'),
        ('recibo', '0002_rename_saldo_recibo_saldo_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='recibo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recibo.recibo'),
        ),
    ]
