# Generated by Django 3.2.6 on 2024-10-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuento', '0002_auto_20241018_0406'),
        ('recibo', '0003_auto_20241018_0406'),
        ('usuarioPadreFamilia', '0002_rename_user_name_usuariopadrefamilia_username_and_more'),
        ('cronograma', '0003_auto_20241018_0406'),
        ('pago', '0004_pago_cronograma_pago_nombre_pago_pago_tipo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cronograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados_pago', to='cronograma.cronograma'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='descuentos',
            field=models.ManyToManyField(related_name='pagos_cronograma', to='descuento.Descuento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recibo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_pago', to='recibo.recibo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados_pago', to='usuarioPadreFamilia.usuariopadrefamilia'),
        ),
    ]
