# Generated by Django 3.2.6 on 2024-10-18 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0005_auto_20241018_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cronograma',
            field=models.CharField(default='Sin cronograma', max_length=100),
        ),
        migrations.RemoveField(
            model_name='pago',
            name='descuentos',
        ),
        migrations.AddField(
            model_name='pago',
            name='descuentos',
            field=models.CharField(default='Sin descuentos', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nombre_pago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recibo',
            field=models.CharField(default='Sin recibo', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario_padre',
            field=models.CharField(default='Usuario no asignado', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
